version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_NAME=todo
      - DB_USER=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo

volumes:
  db_data: